### ISSUE TITLE
twse-crawler: RuntimeError got Future <Future pending> attached to a different loop

### ISSUE THREAD

**Issue by WildfootW** [WildfootW/TradeWiSE#2]
```
twse-crawler-1  | 2023-12-13 12:05:16,197 ERROR Job "process_report (trigger: date[2023-12-13 12:05:16 UTC], next run at: 2023-12-13 12:05:16 UTC)" raised an exception     
twse-crawler-1  | Traceback (most recent call last):                                  
twse-crawler-1  |   File "/usr/local/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job                                          
twse-crawler-1  |     retval = await job.func(*job.args, **job.kwargs)                
twse-crawler-1  |   File "./main.py", line 129, in process_report                     
twse-crawler-1  |     html_dataframe = await crawl_financial_report(ticker_symbol, year, season, report_type)                                                               
twse-crawler-1  |   File "./main.py", line 57, in wrapped                             
twse-crawler-1  |     await limiter.wait()                                            
twse-crawler-1  |   File "./main.py", line 40, in wait                                
twse-crawler-1  |     async with self.lock:                                           
twse-crawler-1  |   File "/usr/local/lib/python3.8/asyncio/locks.py", line 97, in __aenter__                                                                                
twse-crawler-1  |     await self.acquire()                                            
twse-crawler-1  |   File "/usr/local/lib/python3.8/asyncio/locks.py", line 203, in acquire                                                                                  
twse-crawler-1  |     await fut                                                       
twse-crawler-1  | RuntimeError: Task <Task pending name='Task-3' coro=<run_coroutine_job() running at /usr/local/lib/python3.8/site-packages/apscheduler/executors/base_py3.py:30> cb=[AsyncIOExecutor._do_submit_job.<locals>.callback() at /usr/local/lib/python3.8/site-packages/apscheduler/executors/asyncio.py:35]> got Future <Future pending> attached to a different loop
```

**Comment by WildfootW** [comment]
ChatGPT:
> check how and where your event loop is being managed. If you're running this in a container or a service, there might be other factors at play related to how the event loop is initialized and managed. The solution might involve restructuring how your asyncio loop is set up and managed, especially in the context of the containerized environment.

**Comment by WildfootW** [comment]
Seems like main.py in twse-crawler works outside the container
https://github.com/WildfootW/TradeWiSE/commit/07cd141ee1857ef956ee3d679185d49211b948ea
https://github.com/WildfootW/TradeWiSE/commit/c8d2f447fcff0027711bb490434a6bc764d738d5

**Comment by soyccan** [comment]
In your twse-crawler/src/main.py, you initialize a asyncio.Lock object outside any async loop:
```python
class RateLimiter:
    def __init__(self, calls_per_second):
        self.period = 1.0 / calls_per_second
        # Create an asyncio lock for synchronizing access in asynchronous context
        self.lock = asyncio.Lock()    # <-- this line
        self.last_called = time.monotonic()
```

Any asyncio operations should be issued from within a async loop, i.e. inside a coroutine function.
